CREATE TABLE IF NOT EXISTS `cms_files_cat` (
  `id` int(11) NOT NULL auto_increment,
  `id_owner` int(11) NOT NULL default '0',
  `sys_rights_r` bigint(20) unsigned NOT NULL default '0',
  `sys_rights_w` bigint(20) unsigned NOT NULL default '0',
  `sys_rights_d` bigint(20) unsigned NOT NULL default '0',
  `public` tinyint(1) NOT NULL default '1',
  `public_direct_link` tinyint(4) NOT NULL default '0',
  `urgent` tinyint(3) unsigned NOT NULL default '0',
  `urgent_date` datetime default NULL,
  `name` varchar(255) NOT NULL default '',
  `announce` mediumtext NOT NULL,
  `body` mediumtext NOT NULL,
  `position` int(11) unsigned NOT NULL default '0',
  `lang` varchar(3) NOT NULL default 'en',
  `sublink` varchar(128) NOT NULL default '',
  `link_alias` varchar(128) NOT NULL default '',
  `sm_data` blob NOT NULL,
  `id_page` int(11) NOT NULL default '0',
  `num_items` int(11) NOT NULL default '0',
  `num_public_items` int(11) NOT NULL default '0',
  `modified_date` datetime NOT NULL default '0000-00-00 00:00:00',
  `ext_picture` varchar(128) NOT NULL default '',
  `ext_popup_picture` varchar(128) NOT NULL default '',
  `ext_small_picture` varchar(128) NOT NULL default '',
  `id_dataset` int(10) unsigned NOT NULL default '0',
  `details_noindex` tinyint(3) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `i_urgent_date` (`urgent_date`),
  KEY `i_urgent_urgent_date` (`urgent`,`urgent_date`),
  KEY `i_id_owner` (`id_owner`),
  KEY `i_id_page` (`id_page`),
  KEY `i_lang` (`lang`),
  KEY `i_link_alias` (`link_alias`),
  KEY `i_name` (`name`),
  KEY `i_position` (`position`),
  KEY `i_public` (`public`),
  KEY `i_public_direct_link` (`public_direct_link`),
  KEY `i_sublink` (`sublink`),
  KEY `i_sys_rights_d` (`sys_rights_d`),
  KEY `i_sys_rights_r` (`sys_rights_r`),
  KEY `i_sys_rights_w` (`sys_rights_w`),
  FULLTEXT KEY `i_announce` (`announce`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;